sudo: false
language: node_js
node_js:
  - '12'

cache:
  directories:
    - node_modules

addons:
  chrome: stable

notifications:
  email: false

git:
  depth: 3

before_install:
  - npm install -g npm@~6.14.9

install:
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint
  - npm run build:lib